### ISSUE TITLE
how to fix this?

### ISSUE THREAD

**Issue by Mohammadwh** [Bearle/django_private_chat2#19]
* django_private_chat2 version:
* Django version:
* Python version:
* Operating System:

### Description

Describe what you were trying to get done.
Tell us what happened, what went wrong, and what you expected to happen.

### What I Did

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```

Exception inside application: 'ChatConsumer' object has no attribute 'channel_name'
Traceback (most recent call last):
  File "/root/testchat/venv/lib/python3.8/site-packages/channels/staticfiles.py", line 44, in __call__
    return await self.application(scope, receive, send)
  File "/root/testchat/venv/lib/python3.8/site-packages/channels/routing.py", line 71, in __call__
    return await application(scope, receive, send)
  File "/root/testchat/venv/lib/python3.8/site-packages/channels/sessions.py", line 47, in __call__
    return await self.inner(dict(scope, cookies=cookies), receive, send)
  File "/root/testchat/venv/lib/python3.8/site-packages/channels/sessions.py", line 263, in __call__
    return await self.inner(wrapper.scope, receive, wrapper.send)
  File "/root/testchat/venv/lib/python3.8/site-packages/channels/auth.py", line 185, in __call__
    return await super().__call__(scope, receive, send)
  File "/root/testchat/venv/lib/python3.8/site-packages/channels/middleware.py", line 26, in __call__
    return await self.inner(scope, receive, send)
  File "/root/testchat/venv/lib/python3.8/site-packages/channels/routing.py", line 150, in __call__
    return await application(
  File "/root/testchat/venv/lib/python3.8/site-packages/channels/consumer.py", line 94, in app
    return await consumer(scope, receive, send)
  File "/root/testchat/venv/lib/python3.8/site-packages/channels/consumer.py", line 62, in __call__
    await await_many_dispatch([receive], self.dispatch)
  File "/root/testchat/venv/lib/python3.8/site-packages/channels/utils.py", line 51, in await_many_dispatch
    await dispatch(result)
  File "/root/testchat/venv/lib/python3.8/site-packages/channels/consumer.py", line 73, in dispatch
    await handler(message)
  File "/root/testchat/venv/lib/python3.8/site-packages/channels/generic/websocket.py", line 173, in websocket_connect
    await self.connect()
  File "/root/testchat/venv/lib/python3.8/site-packages/django_private_chat2/consumers.py", line 138, in connect
    logger.info(f"User {self.user.pk} connected, adding {self.channel_name} to {self.group_name}")
AttributeError: 'ChatConsumer' object has no attribute 'channel_name'

hi how i can fix this?

**Comment by MykolaZ12** [comment]
Try add this in settigns.py
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels.layers.InMemoryChannelLayer'
    }
}

**Comment by delneg** [comment]
Closing as stale, please read https://channels.readthedocs.io/en/stable/ to learn about how Django Channels works.
