### ISSUE TITLE
Migration error on MySql

### ISSUE THREAD

**Issue by yunusc5n** [Bearle/django_private_chat2#2]
* django_private_chat2 version: 2 0.1.2
* Django version: 3.1.7
* Python version: 3.8
* Operating System: W10 20h2

### Description
 **Giving errors in the third migration.**

Applying django_private_chat2.0003_auto_20210323_1410...Traceback (most recent call last):
  File "C:\Users\Yunus\PycharmProjects\yeye\venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\Yunus\PycharmProjects\yeye\venv\lib\site-packages\django\db\backends\mysql\base.py", line 73, in exec
ute
    return self.cursor.execute(query, args)
  File "C:\Users\Yunus\PycharmProjects\yeye\venv\lib\site-packages\MySQLdb\cursors.py", line 209, in execute
    res = self._query(query)
  File "C:\Users\Yunus\PycharmProjects\yeye\venv\lib\site-packages\MySQLdb\cursors.py", line 315, in _query
    db.query(q)
  File "C:\Users\Yunus\PycharmProjects\yeye\venv\lib\site-packages\MySQLdb\connections.py", line 239, in query
    _mysql.connection.query(self, query)
MySQLdb._exceptions.OperationalError: (1553, "Cannot drop index 'Unique dialog': needed in a foreign key constraint")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    main()
  File "manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "C:\Users\Yunus\PycharmProjects\yeye\venv\lib\site-packages\django\core\management\__init__.py", line 401, in e
xecute_from_command_line
    utility.execute()
  File "C:\Users\Yunus\PycharmProjects\yeye\venv\lib\site-packages\django\core\management\__init__.py", line 395, in e
xecute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "C:\Users\Yunus\PycharmProjects\yeye\venv\lib\site-packages\django\core\management\base.py", line 330, in run_f
rom_argv
    self.execute(*args, **cmd_options)
  File "C:\Users\Yunus\PycharmProjects\yeye\venv\lib\site-packages\django\core\management\base.py", line 371, in execu
te
    output = self.handle(*args, **options)
  File "C:\Users\Yunus\PycharmProjects\yeye\venv\lib\site-packages\django\core\management\base.py", line 85, in wrappe
d
    res = handle_func(*args, **kwargs)
  File "C:\Users\Yunus\PycharmProjects\yeye\venv\lib\site-packages\django\core\management\commands\migrate.py", line 2
43, in handle
    post_migrate_state = executor.migrate(
  File "C:\Users\Yunus\PycharmProjects\yeye\venv\lib\site-packages\django\db\migrations\executor.py", line 117, in mig
rate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "C:\Users\Yunus\PycharmProjects\yeye\venv\lib\site-packages\django\db\migrations\executor.py", line 147, in _mi
grate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "C:\Users\Yunus\PycharmProjects\yeye\venv\lib\site-packages\django\db\migrations\executor.py", line 227, in app
ly_migration
    state = migration.apply(state, schema_editor)
  File "C:\Users\Yunus\PycharmProjects\yeye\venv\lib\site-packages\django\db\migrations\migration.py", line 124, in ap
ply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "C:\Users\Yunus\PycharmProjects\yeye\venv\lib\site-packages\django\db\migrations\operations\models.py", line 84
3, in database_forwards
    schema_editor.remove_constraint(model, constraint)
  File "C:\Users\Yunus\PycharmProjects\yeye\venv\lib\site-packages\django\db\backends\base\schema.py", line 368, in re
move_constraint
    self.execute(sql)
  File "C:\Users\Yunus\PycharmProjects\yeye\venv\lib\site-packages\django\db\backends\base\schema.py", line 142, in ex
ecute
    cursor.execute(sql, params)
  File "C:\Users\Yunus\PycharmProjects\yeye\venv\lib\site-packages\django\db\backends\utils.py", line 98, in execute
    return super().execute(sql, params)
  File "C:\Users\Yunus\PycharmProjects\yeye\venv\lib\site-packages\django\db\backends\utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "C:\Users\Yunus\PycharmProjects\yeye\venv\lib\site-packages\django\db\backends\utils.py", line 75, in _execute_
with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\Yunus\PycharmProjects\yeye\venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\Yunus\PycharmProjects\yeye\venv\lib\site-packages\django\db\utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\Yunus\PycharmProjects\yeye\venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\Yunus\PycharmProjects\yeye\venv\lib\site-packages\django\db\backends\mysql\base.py", line 73, in exec
ute
    return self.cursor.execute(query, args)
  File "C:\Users\Yunus\PycharmProjects\yeye\venv\lib\site-packages\MySQLdb\cursors.py", line 209, in execute
    res = self._query(query)
  File "C:\Users\Yunus\PycharmProjects\yeye\venv\lib\site-packages\MySQLdb\cursors.py", line 315, in _query
    db.query(q)
  File "C:\Users\Yunus\PycharmProjects\yeye\venv\lib\site-packages\MySQLdb\connections.py", line 239, in query
    _mysql.connection.query(self, query)
django.db.utils.OperationalError: (1553, "Cannot drop index 'Unique dialog': needed in a foreign key constraint")

### What I Did

I just tried to migrate after the setup.

**Comment by delneg** [comment]
Checking now ...

**Comment by delneg** [comment]
Please try 0.1.3

**Comment by yunusc5n** [comment]
0.1.3 is good to go, thank you.
